### ISSUE TITLE
How can I contribute

### ISSUE THREAD

**Issue by cheesimp** [cashapp/cmmc#8]
I'd like to debug this [issue](https://github.com/cashapp/cmmc/issues/7) by myself but there is no information about how to contribute / how to run the project locally.

**Comment by stanistan** [comment]
I added some basics to [here](https://cashapp.github.io/cmmc/contributing/) in https://github.com/cashapp/cmmc/commit/145fa26d45cc6214a17a753caecf8ab86e0e62a7.

**Comment by cheesimp** [comment]
Amazing @stanistan thanks!
